// Bulk import script for migrating old profiles to the backend API
// Instructions:
// 1. Replace any imported image variables (e.g., abhishekKrImg) with actual URLs or filenames as needed.
// 2. Run: node bulkImportProfiles.js

import fetch from 'node-fetch';

const API_URL = 'http://localhost:3001/api/directory';

const directoryPeople = [
  {
    img: '/assets/Abhishek KR.jpeg',
    imgPosition: 'center 16%',
    name: 'Abhishek KR',
    roll: 'ROLL: 355U1238002',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-a',
  },
  {
    img: '/assets/Anbuselvan K.jpeg',
    imgPosition: 'center 16%',
    name: 'Anbuselvan K',
    roll: 'ROLL: 35523U18006',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-a',
  },
  {
    img: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 18%',
    coverPosition: 'center 45%',
    name: 'Arthur Pendel',
    roll: 'ROLL: HIS-2026-077',
    department: 'History',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-b',
  },
  {
    img: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 18%',
    coverPosition: 'center 46%',
    name: 'Cora Night',
    roll: 'ROLL: MUS-2026-091',
    department: 'Music',
    batch: '2026',
    type: 'student',
    gender: 'girls',
    classSection: 'class-b',
  },
  {
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 16%',
    coverPosition: 'center 52%',
    name: 'David Sterling',
    roll: 'ROLL: SCI-2026-201',
    department: 'Data Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-a',
  },
  {
    img: '/assets/Dhanush V.jpeg',
    imgPosition: 'center 16%',
    name: 'Dhanush V',
    roll: 'ROLL: 35523U18016',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-a',
  },
  {
    img: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 16%',
    coverPosition: 'center 48%',
    name: 'Dr. Ethan Vale',
    roll: 'ID: FAC-ART-007',
    department: 'Visual Communication',
    batch: 'Faculty',
    type: 'faculty',
  },
  {
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 18%',
    coverPosition: 'center 46%',
    name: 'Elara Vance',
    roll: 'ROLL: ART-2026-112',
    department: 'Fine Arts',
    batch: '2026',
    type: 'student',
    gender: 'girls',
    classSection: 'class-a',
  },
  {
    img: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 18%',
    coverPosition: 'center 48%',
    name: 'Isabella Hunt',
    roll: 'ROLL: LIT-2026-022',
    department: 'Literature',
    batch: '2026',
    type: 'student',
    gender: 'girls',
    classSection: 'class-b',
  },
  {
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 18%',
    coverPosition: 'center 50%',
    name: 'Julian Thorne',
    roll: 'ROLL: ARCH-2026-004',
    department: 'Architecture',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-a',
  },
  {
    img: '/assets/Kumaraguru J.jpeg',
    imgPosition: 'center 16%',
    name: 'kumaraguru J',
    roll: 'ROLL: 35523U18033',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-a',
  },
  {
    img: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 20%',
    coverPosition: 'center 48%',
    name: 'Leo Sterling',
    roll: 'ROLL: LAW-2026-003',
    department: 'Law',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-a',
  },
  {
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 16%',
    coverPosition: 'center 44%',
    name: 'Marcus Chen',
    roll: 'ROLL: ENG-2026-089',
    department: 'Computer Engineering',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-b',
  },
  {
    img: '/assets/Mohanaaswath M.jpeg',
    imgPosition: 'center 16%',
    name: 'Mohanaaswath M',
    roll: 'ROLL: 35523U18041',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-a',
  },
  {
    img: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 16%',
    coverPosition: 'center 50%',
    name: 'Nia Okoro',
    roll: 'ROLL: ECO-2026-154',
    department: 'Economics',
    batch: '2026',
    type: 'student',
    gender: 'girls',
    classSection: 'class-a',
  },
  {
    img: '/assets/Nithin Kishore T.jpeg',
    imgPosition: 'center 16%',
    name: 'Nithin Kishore T',
    roll: 'ROLL: CSE-2026-205',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-a',
  },
    {
      img: '/assets/Nivetha G.jpeg',
      imgPosition: 'center 16%',
      name: 'Nivetha G',
      roll: '35523U18061',
      department: 'Computer Science',
      batch: '2026',
      type: 'student',
      gender: 'girls',
      classSection: 'class-a',
    },
  {
    img: '/assets/Poovarasan K.jpeg',
    imgPosition: 'center 16%',
    name: 'Poovarasan K',
    roll: '35523U18053',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-b',
  },
  {
    img: '/assets/Pradeep P.jpeg',
    imgPosition: 'center 16%',
    name: 'Pradeep P',
    roll: '35523U18055',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-b',
  },
  {
    img: '/assets/Senbagapriya G.jpeg',
    imgPosition: 'center 16%',
    name: 'Senbagapriya G',
    roll: '35523U18061',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'girls',
    classSection: 'class-b',
  },
  {
    img: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 18%',
    coverPosition: 'center 45%',
    name: 'Prof. Mira Kline',
    roll: 'ID: FAC-ENG-012',
    department: 'Systems Engineering',
    batch: 'Faculty',
    type: 'faculty',
  },
  {
    img: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=500&auto=format&fit=crop',
    coverImg: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1600&auto=format&fit=crop',
    imgPosition: 'center 20%',
    coverPosition: 'center 45%',
    name: 'Sophia Rossi',
    roll: 'ROLL: DES-2026-045',
    department: 'Design',
    batch: '2026',
    type: 'student',
    gender: 'girls',
    classSection: 'class-a',
  },
  {
    img: '/assets/Sonthosh M.jpeg',
    imgPosition: 'center 16%',
    name: 'Sonthosh M',
    roll: 'ROLL: 35523U18073',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-b',
  },
  {
    img: '/assets/Umamagesh M.jpeg',
    imgPosition: 'center 16%',
    name: 'Umamagesh M',
    roll: '35523U18061',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'girls',
    classSection: 'class-b',
  },
  {
    img: '/assets/Vikram M.jpeg',
    imgPosition: 'center 16%',
    name: 'Vikram M',
    roll: '35523U18099',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-b',
  },
  {
    img: '/assets/Rajesh S.jpeg',
    imgPosition: 'center 16%',
    name: 'Rajesh S',
    roll: '35523U18061',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-b',
  },
  {
    img: '/assets/Sounder Raj A.jpeg',
    imgPosition: 'center 16%',
    name: 'Sounder Raj A',
    roll: '35523U18081',
    department: 'Computer Science',
    batch: '2026',
    type: 'student',
    gender: 'boyz',
    classSection: 'class-b',
  },
];

async function importProfiles() {
  for (const profile of directoryPeople) {
    // Map fields to match backend expectations
    const payload = {
      name: profile.name,
      roll: profile.roll,
      department: profile.department,
      batch: profile.batch,
      type: profile.type,
      gender: profile.gender,
      classSection: profile.classSection,
      img: profile.img,
      // Add coverImg, imgPosition, coverPosition if your backend supports them
    };
    try {
      const res = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (res.ok) {
        console.log(`Imported: ${profile.name}`);
      } else {
        const err = await res.text();
        console.error(`Failed: ${profile.name} — ${res.status} ${err}`);
      }
    } catch (e) {
      console.error(`Error importing ${profile.name}:`, e.message);
    }
  }
}

importProfiles();
